# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: 'src'
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: knowrob/rosprolog
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: knowrob/ease_ontology
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: knowrob/rosowl
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: knowrob/genowl
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: ease-crc/dul
    
    - uses: actions/checkout@v1
      with:
        path: 'src'
        repository: code-iai/iai_common_msgs
    
    # Runs a single command using the runners shell
    - name: Setup catkin workspace
      uses: janbernloehr/github-setup-catkin@patch-1
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax.
        ros-version: melodic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE
    
    # build the workspace
    - run: catkin_make_isolated -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
