# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: 'src/knowrob'
    
    - uses: actions/checkout@v2
      with:
        path: 'src/rosprolog'
        repository: daniel86/rosprolog
    
    - uses: actions/checkout@v2
      with:
        path: 'src/ease_ontology'
        repository: knowrob/ease_ontology
    
    - uses: actions/checkout@v2
      with:
        path: 'src/dul'
        repository: ease-crc/dul
    
    - uses: actions/checkout@v2
      with:
        path: 'src/iai_common_msgs'
        repository: code-iai/iai_common_msgs
    
    # Runs a single command using the runners shell
    - name: Setup catkin workspace
      uses: janbernloehr/github-setup-catkin@patch-1
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax.
        ros-version: melodic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE
    
    # build the workspace
    - run: catkin_make_isolated
    
    - name: Run tests
      shell: bash
      run: |
        sudo systemctl start mongod
        roscore &
        source $GITHUB_WORKSPACE/devel_isolated/setup.bash
        rosrun rosprolog rosprolog-test -o junit-knowrob.xml knowrob
      
    - name: Report jUnit Annotations as Github Actions Annotations
      uses: shyim/junit-report-annotations-action@0.1.5
      with:
        path: junit-*.xml
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        
    #source $GITHUB_WORKSPACE/devel_isolated/setup.bash
    #/usr/bin/swipl -q -f $GITHUB_WORKSPACE/${PL_INIT} \
    #-g "ensure_loaded('$GITHUB_WORKSPACE/${PL_INIT}'),ensure_loaded('$GITHUB_WORKSPACE/${PL_TEST}')" \
    #-t "setup_call_cleanup(true, rospl_run_tests(knowrob,[xunit('xunit.xml')]), halt)"
    #ls .
    
    # . $GITHUB_WORKSPACE/src/rosprolog/scripts/rosprolog-test -o xunit.xml knowrob
    #- run: |
    #    source $GITHUB_WORKSPACE/devel_isolated/setup.bash
    #    roslaunch knowrob knowrob.launch
